#!/bin/sh
#feh --no-fehbg --bg-scale '/home/nils/Bilder/Background/mrfluffy-dev-wallpapers/066.jpg' 
feh --no-fehbg --bg-scale '/home/nils/Bilder/Background/wiener234/040.png' 
# feh --no-fehbg --bg-scale '/home/nils/Bilder/Background/mrfluffy-dev-wallpapers/091.jpg' 
# feh --no-fehbg --bg-scale '/home/nils/Bilder/Background/mrfluffy-dev-wallpapers/091.jpg' 
# feh --no-fehbg --bg-scale '/home/nils/Bilder/Background/mrfluffy-dev-wallpapers/070.jpg' 

